//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUploadWithFormData.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal_Image
    {
        public System.Guid Id { get; set; }
        public string ImageUrl { get; set; }
        public System.Guid DealId { get; set; }
    
        public virtual Deal Deal { get; set; }
    }
}
